
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello
  namespace: general
spec:
  selector:
    app: hello-node
  ports:
  - name: http
    targetPort: 8080
    port: 8080





 
