apiVersion: v1
kind: Service
metadata:
  name: integrator-service
  labels:
    app: integrator-server
  namespace: general
spec:
  selector:
    app: integrator-server
  ports:
    - name: http
      targetPort: 8080
      port: 8080