apiVersion: v1
kind: Service
metadata:
  name: integrator-service
  labels:
    app: integrator-server
  namespace: general
spec:
  selector:
    app: integrator-server
  ports:
    - name: http
      targetPort: 8080
      port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: integrator-service-metrics
  labels:
    app: integrator-server
    collect-metrics: "true"
  namespace: general
spec:
  selector:
    app: integrator-server
  ports:
    - name: http-metrics
      targetPort: 8081
      port: 8081