
apiVersion: v1
kind: Service
metadata:
  name: login-ui
  labels:
    app: login-ui
  namespace: general
spec:
  selector:
    app: login-ui
  ports:
  - name: http
    targetPort: 80
    port: 80





 
