apiVersion: v1
kind: Service
metadata:
  name: login-ui
  labels:
    app: login-ui
  namespace: general
spec:
  selector:
    app: login-ui
  ports:
    - name: http
      targetPort: 8080
      port: 8080
---
kind: Endpoints
apiVersion: v1
metadata:
  name: login-ui
  namespace: general
  labels:
    app: login-ui
    environment: localdevelopment
subsets:
  - addresses:
      - ip: 192.168.178.59
    ports:
      - port: 8080
        name: http