apiVersion: v1
kind: PersistentVolume
metadata:
  name: maria-pv-volume
  labels:
    type: local
  namespace: general
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maria-pv-claim
  namespace: general
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
