apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  labels:
   app: auth-server
spec:
  selector:
    matchLabels:  
      app: auth-server
  template:
    metadata:
      labels: 
        app: auth-server
    spec:
      containers:
      - image: evert1981/auth-server:latest
        imagePullPolicy: Always
        name: auth-server
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: general-configmap
                key: spring.datasource.url
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: username
          - name: LOGIN_URL
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: login.url

          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: password
        ports:
        - containerPort: 8080
          name: http      
