apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  labels:
   app: auth-server
  namespace: general
spec:
  selector:
    matchLabels:  
      app: auth-server
  template:
    metadata:
      labels: 
        app: auth-server
    spec:
      containers:
      - image: evert1981/auth-server:latest
        imagePullPolicy: Always
        name: auth-server
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: general-configmap
                key: datasource.url.authserver
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: dbusername
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: dbpassword
          - name: LOGIN_URL
            valueFrom:
              configMapKeyRef:
                name: general-configmap
                key: login.url
          - name: JWT_SECRETKEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: jwtsecret
        ports:
        - containerPort: 8080
          name: http      
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 20