apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrator-server
  labels:
   app: integrator-server
  namespace: general
spec:
  selector:
    matchLabels:  
      app: integrator-server
  template:
    metadata:
      labels: 
        app: integrator-server
    spec:
      containers:
      - image: evert1981/integrator:latest
        imagePullPolicy: Always
        name: integrator
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: general-configmap
                key: datasource.url.intergrator
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: integrator-secret
                key: dbusername
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: integrator-secret
                key: dbpassword
          - name: JWT_SECRETKEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: jwtsecret
        ports:
        - containerPort: 8080
          name: http      
