apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-ui
  labels:
   app: login-ui
  namespace: general
spec:
  selector:
    matchLabels:  
      app: login-ui
  template:
    metadata:
      labels: 
        app: login-ui
    spec:
      containers:
      - image: evert1981/login-ui:latest
        imagePullPolicy: Always
        name: login-ui
        ports:
        - containerPort: 80
          name: http      
