apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - http:
      paths:
      - path: /hello
        backend:
          serviceName: hello-service
          servicePort: http  
      - path: /auth
        backend:
          serviceName: auth-service
          servicePort: http
      - path: /login
        backend:
          serviceName: login-ui
          servicePort: http


